### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Xvezda** [Xvezda/xvzd-wargame#3]
- [x] 쪽지 읽음처리 하기
- [x] 안읽은거 있으면 로그인 표시에 알림 띄워주기
- [x] `prestart.sh`는 redis먼저
- [x] 관리자 브라우저 정보 보여주기
- [x] `render_template`기본 model 넘겨주기 래퍼함수
- [x] 안쓰는 파일 정리하기
- [x] `X-Frame-Options` `X-XSS-Protection` 헤더 세팅
- [x] `<title>` 수정
- [x] 로그인, 가입 페이지 디자인 정리
- [x] 정상작동 확인, 재빌드
- [x] anti hack 필터 강화
- [ ] ~실시간 처리 (시간남으면)~
